---
- name: Install Prometheus and Grafana
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Check network connectivity
      run: curl -I https://archive.ubuntu.com

    - name: Update the package manager
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      apt:
        name:
          - wget
          - tar
          - curl
        state: present

    - name: Create Prometheus user
      user:
        name: prometheus
        system: yes
        shell: /sbin/nologin

    - name: Download and install Prometheus
      block:
        - name: Download Prometheus
          get_url:
            url: https://github.com/prometheus/prometheus/releases/latest/download/prometheus-2.36.0.linux-amd64.tar.gz
            dest: /tmp/prometheus.tar.gz

        - name: Extract Prometheus
          unarchive:
            src: /tmp/prometheus.tar.gz
            dest: /usr/local/bin/
            remote_src: yes

        - name: Move Prometheus binary files
          command: mv /usr/local/bin/prometheus-* /usr/local/bin/prometheus

        - name: Create Prometheus configuration directory
          file:
            path: /etc/prometheus
            state: directory

        - name: Copy Prometheus configuration file
          copy:
            src: prometheus.yml
            dest: /etc/prometheus/prometheus.yml

        - name: Create Prometheus systemd service file
          copy:
            dest: /etc/systemd/system/prometheus.service
            content: |
              [Unit]
              Description=Prometheus
              After=network.target

              [Service]
              User=prometheus
              ExecStart=/usr/local/bin/prometheus/prometheus \
                --config.file=/etc/prometheus/prometheus.yml \
                --storage.tsdb.path=/var/lib/prometheus/data

              [Install]
              WantedBy=multi-user.target

    - name: Start and enable Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Install Grafana
      block:
        - name: Add Grafana APT repository
          apt_repository:
            repo: "deb https://packages.grafana.com/oss/release/deb stable main"
            state: present

        - name: Install Grafana
          apt:
            name: grafana
            state: present

        - name: Start and enable Grafana
          systemd:
            name: grafana-server
            state: started
            enabled: yes

    - name: Open firewall for Prometheus and Grafana
      ufw:
        rule: allow
        name: "Open HTTP"
        state: enabled
