name: DEPI Final Project

on:
  push:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  SSH_KEY_NAME: "github-actions-key"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Check for Terraform Installation
        id: check_terraform
        run: |
          if command -v terraform &> /dev/null; then
            echo "Terraform is already installed."
            echo "terraform_cache_exists=true" >> $GITHUB_ENV
          else
            echo "Terraform not found. Installing..."
            echo "terraform_cache_exists=false" >> $GITHUB_ENV
          fi

      - name: Setup Terraform
        if: env.terraform_cache_exists == 'false'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Cache SSH Client Installation
        id: cache_ssh_client
        run: |
          if ! command -v ssh &> /dev/null; then
            echo "SSH client not found. Installing..."
            sudo apt-get update
            sudo apt-get install -y openssh-client
          else
            echo "SSH client is already installed."
          fi

      - name: Check for SSH Key Cache
        id: check_ssh_cache
        run: |
          if [ -f ~/.ssh/github-actions-key ]; then
            echo "SSH key cache exists."
            echo "ssh_cache_exists=true" >> $GITHUB_ENV
          else
            echo "ssh_cache_exists=false" >> $GITHUB_ENV
          fi

      - name: Generate SSH Key
        if: env.ssh_cache_exists == 'false'
        run: |
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/github-actions-key -N "" || echo "SSH key already exists"

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          cat ~/.ssh/github-actions-key.pub | tee -a ~/.ssh/authorized_keys

      - name: Cache SSH Keys
        if: env.ssh_cache_exists == 'false'
        uses: actions/cache@v3
        with:
          path: ~/.ssh/github-actions-key*
          key: ${{ runner.os }}-ssh-keys-${{ hashFiles('~/.ssh/github-actions-key.pub') }}
          restore-keys: |
            ${{ runner.os }}-ssh-keys-
      
      - name: Check for Terraform State Cache
        id: check_tf_cache
        run: |
          if [ -d .terraform ]; then
            echo "Terraform state cache exists."
            echo "tf_cache_exists=true" >> $GITHUB_ENV
          else
            echo "tf_cache_exists=false" >> $GITHUB_ENV
          fi
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
        run: terraform apply -auto-approve

      - name: Get Instance IP
        id: instance_ip
        run: echo "INSTANCE_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV

      - name: Cache Terraform State
        if:  env.tf_cache_exists == 'false'
        uses: actions/cache@v3
        with:
          path: .terraform/
          key: ${{ runner.os }}-terraform-state-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-state-

      - name: Cache Ansible Installation
        uses: actions/cache@v3
        with:
          path: ~/.ansible
          key: ${{ runner.os }}-ansible-${{ hashFiles('**/requirements.yml') }}
          restore-keys: |
            ${{ runner.os }}-ansible-

      - name: Install Ansible
        run: |
          if [ ! -d ~/.ansible ]; then
            sudo apt-get install -y ansible
          fi

      - name: Run Ansible Playbook
        run: |
            cd ./ansible
            ansible-playbook -i "${{ env.INSTANCE_IP }}," main.yml --private-key ~/.ssh/${{ env.SSH_KEY_NAME }}