name: DEPI Final Project

on:
  push:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SSH_PRIVATE_KEY_PATH: "~/.ssh/id_rsa"
  SSH_PUBLIC_KEY_PATH: "~/.ssh/id_rsa.pub"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-server ansible

      - name: Generate SSH key
        run: |
          ssh-keygen -t rsa -b 4096 -f ${{ env.SSH_PRIVATE_KEY_PATH }} -C "mu@depi.com"
          chmod 600 ${{ env.SSH_PRIVATE_KEY_PATH }}

      - name: Terraform Init
        run: |
          cd ./terraform 
          terraform init

      - name: Terraform Apply (manual approval)
        run: |
          terraform apply -var="aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" \
                            -var="aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}" \
                            -var="key_path=${{ env.SSH_PUBLIC_KEY_PATH }}"

      - name: Save Terraform Outputs
        run: |
          terraform output -json | awk -F'"' '{print $4}' > ec2_user.txt
          terraform output -json | awk -F'"' '{print $6}' > ec2_public_ip.txt
          export EC2_USER=$(cat ec2_user.txt)
          export EC2_PUBLIC_IP=$(cat ec2_public_ip.txt)
          echo "EC2_USER=$EC2_USER"
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP"

      - name: Run Ansible playbook
        run: |
          cd ./ansible && ansible-playbook -i ansible/hosts ansible/main.yml
